# Generated by Django 2.2.10 on 2020-05-28 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miembro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='grupo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='grupo.Grupo'),
        ),
    ]
