# Generated by Django 2.2.10 on 2020-05-28 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grupo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('estatus', models.CharField(choices=[('DESEMBOLSADA', 'DESEMBOLSADA'), ('CERRADA', 'CERRADA')], default='DESEMBOLSADA', max_length=15)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('grupo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupo.Grupo')),
            ],
        ),
    ]
