# Generated by Django 2.2.10 on 2020-05-28 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuenta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioPago',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('num_pago', models.IntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha_pago', models.DateField()),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('PAGADO', 'PAGADO'), ('PARCIAL', 'PARCIAL'), ('ATRASADO', 'ATRASADO')], default='PENDIENTE', max_length=15)),
                ('cuenta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuenta.Cuenta')),
            ],
        ),
    ]
